### ISSUE TITLE
在 vue 中使用时的尴尬问题。

### ISSUE THREAD

**Issue by YaoaY** [taoqf/tencent-wx-jssdk#1]
```
import { Component } from 'vue-property-decorator'
import template from './app.vue'

//import wx = require('weixin-js-sdk');

@Component({
    name: 'page-app',
    mixins: [template]
})
export default class App extends Vue {
    created(){        
        wx.config({
            debug:true,
            appId:"",
            timestamp:1,
            nonceStr:"",
            signature:"",
            jsApiList:[]
        });
    }
}
```

如果不加 `import wx = require('weixin-js-sdk');` ，运行时出错：

> [Vue warn]: Error in created hook: "ReferenceError: wx is not defined"

加上这句运行是没问题了，但是键入 wx. 就没有智能提示了。

**Comment by taoqf** [comment]
readme中的两种方法不行吗？
```ts
import { config } from 'tencent-wx-jssdk';

config({
	debug: true,
	appId: "",
	timestamp: 1,
	nonceStr: "",
	signature: "",
	jsApiList: []
});
```
或者
```ts
import * as wx from 'tencent-wx-jssdk';

wx.config({
	debug: true,
	appId: "",
	timestamp: 1,
	nonceStr: "",
	signature: "",
	jsApiList: []
});
```
再或者在tsconfig.json中加上
```json
{
	"compilerOptions": {
		"types": [
			"tencent-wx-jssdk"
		]
	}
}
```
试试行不行。
readme中已经写了用法了，难道有问题吗？我测试过是可以的。
多谢反馈。

**Comment by YaoaY** [comment]
试了一下，这样的用法运行时出现错误：
```
Uncaught TypeError: Cannot read property 'title' of undefined
    at eval (index.js?9167:1)
    at Object.eval (index.js?9167:1)
    at eval (index.js?9167:1)
    at eval (index.js?9167:1)
    at Object.<anonymous> (app.js:1248)
    at __webpack_require__ (app.js:699)
    at fn (app.js:112)
    at eval (app.ts?500e:6)
    at Object.<anonymous> (app.js:1075)
    at __webpack_require__ (app.js:699)
```

**Comment by taoqf** [comment]
`
import wx = require('weixin-js-sdk');
`
这种写法我测了一下，是会有提示的，是不是typescript版本问题？我用的[vscode](http://www.typescriptlang.org/)
我没有vue的经验，测试环境不会搭。

**Comment by taoqf** [comment]
> Uncaught TypeError: Cannot read property 'title' of undefined

这个错是jssdk里的吗？我看不出来。如果是的话，说明至少引用是可以了，只是可能是js文件里哪里有bug
1.2.1版本的在微信公众平台的文档里好像还没提，可能不算是稳定版本也说不定。

**Comment by taoqf** [comment]
我查了一下sdk的源码，里面用到title的地方共有七处，有一处是是window.document.title.如果不是在浏览器里，环境里面没有window的话可能是会有问题。另外六处分别是

1. `onMenuShareTimeline`参数中有两个地方，如果参数不传会有异常。如果在ts里用，提前就会发现该问题。
2. `onMenuShareAppMessage`有一处。同上
3. `onMenuShareQQ`有一处，同上。
4. `onMenuShareQZone`有一处，同上。
5. `onMenuShareWeibo`有一处，同上。

所以，如果是sdk中报的错，如果是用ts写的话，一定是第一处全局的window获取有问题了。而window对象是通过 `this` 关键字获取的。所以你那里仍然有问题的话，查一查是不是`this`获取到的不是windows

**Comment by YaoaY** [comment]
感谢回复。

现在的情况是这样的。
使用 `tencent-wx-jssdk` 有智能提示但会出错，降级到1.2.0试了一下也还是那个 `title` 的错误。
我直接使用 `import wx = require('weixin-js-sdk');` ，编译和运行都是正常的，但没有智能提示，实际上这个时候与`tencent-wx-jssdk`没有关系了，等于就是单纯的使用了weixin-js-sdk。

我也是用的VSCode ，TS版本是2.4.2。

**Comment by YaoaY** [comment]
另外我看到VSCode在你的 index.d.ts 里有一句错误提示。

`declare var wx = jWeixin;` 
这句提示：
> [ts] Initializers are not allowed in ambient contexts.

刚接触TS没多久，不是太懂，再次感谢。

**Comment by YaoaY** [comment]
所以我的解决方案就是。。。

写代码的时候注释掉`import wx = require('weixin-js-sdk');`，利用你的智能提示。
写完取消注释。

哈哈。。。

**Comment by taoqf** [comment]
我这里一直用的最新版本的ts。你那里不提示应该是ts版本的问题。另外vs上还有一个[插件](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)，推荐使用.
我看了下 [weixin-js-sdk](https://github.com/yanxi-me/weixin-js-sdk)，你那里不报错应该是因为这位作者修改了原代码，修改成commonjs格式了。原版的文件是amd的。
webpack似乎一直对amd支持不大好，我吸取[weixin-js-sdk](https://github.com/yanxi-me/weixin-js-sdk)作者[yanxi-me](https://github.com/yanxi-me)的经验，改为umd格式的，你有时间的话能否再测一下我刚发布的新版本可以用了吗？
非常感谢。

**Comment by taoqf** [comment]
> 另外我看到VSCode在你的 index.d.ts 里有一句错误提示...

在你的tsconfig.json中加上这个配置试试。
`"skipLibCheck": true`

**Comment by YaoaY** [comment]
刚才试了最新的版本，但是还是那个问题。
我把问题重现放上来了，你可以试试看
[https://github.com/YaoaY/vue-ts-wxjssdk-issue](https://github.com/YaoaY/vue-ts-wxjssdk-issue)

**Comment by taoqf** [comment]
Add this into your tsconfig.json:

```json
"skipLibCheck": true
```

and update `tencent-wx-jssdk` to latest version,   `npm test` will succeed now.
Thanks.
