### ISSUE TITLE
upgrade 1.3.0

### ISSUE THREAD

**Issue by jiangyoucai** [taoqf/tencent-wx-jssdk#2]
https://res.wx.qq.com/open/js/jweixin-1.3.0.js
jweixin-1.3.0 is release

**Comment by taoqf** [comment]
updated already.

**Comment by Array-Huang** [comment]
你们是怎么知道更新到1.3的啊？明明文档上还写着1.2.0

**Comment by taoqf** [comment]
upgrade to [1.3.1](https://res.wx.qq.com/open/js/jweixin-1.3.1.js).
