### ISSUE TITLE
引入编译报错

### ISSUE THREAD

**Issue by wlgshf** [taoqf/tencent-wx-jssdk#5]
ERROR in node_modules/tencent-wx-jssdk/index.d.ts(502,30): error TS2304: Cannot find name 'IchooseCard'.

这是什么问题啊?

**Comment by wlgshf** [comment]
是不是写错了 应该是 chooseCard

**Comment by wlgshf** [comment]
找到了 发现你chooseCard有个大小写没对应

interface IChooseCard extends BaseParams {   
function chooseCard(params: IchooseCard): void;

**Comment by taoqf** [comment]
Thanks, pls try again now, i've published new version.
